"""Corpus, query set, and qrels loading — the tool's inputs.

Minimum input is a **corpus alone**: queries can be auto-sampled (held-out) from
it, and recall ground truth is generated by the tool (brute-force / exact). A
`--qrels` file is OPTIONAL and only unlocks NDCG/MAP relevance scoring.

Supported corpus formats (auto-detected by extension):
- JSONL: one document per line, {"id": ..., "text": ..., "vector": [...]?}
- JSON:  a list of such documents

A document may carry a precomputed `vector` (dense) and/or `text` (sparse/dense
via ingest model). Which field a mode uses is the mode's concern.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Iterator


@dataclass
class Document:
    id: str
    text: str | None = None
    vector: list[float] | None = None
    fields: dict[str, Any] = field(default_factory=dict)


@dataclass
class Query:
    id: str
    text: str | None = None
    vector: list[float] | None = None


@dataclass
class QuerySet:
    queries: list[Query]

    def __len__(self) -> int:
        return len(self.queries)

    def __iter__(self) -> Iterator[Query]:
        return iter(self.queries)


# query_id -> {doc_id: graded_relevance (int, >=1 relevant)}
Qrels = dict[str, dict[str, int]]


@dataclass
class Corpus:
    documents: list[Document]
    dim: int | None = None  # embedding dimensionality if vectors present

    def __len__(self) -> int:
        return len(self.documents)

    @property
    def has_vectors(self) -> bool:
        return bool(self.documents) and self.documents[0].vector is not None

    @property
    def has_text(self) -> bool:
        return bool(self.documents) and self.documents[0].text is not None


def load_corpus(path: str | Path) -> Corpus:
    """Load a JSON/JSONL corpus. Infers dim from the first vector present."""
    docs = list(_iter_docs(Path(path)))
    dim = None
    for d in docs:
        if d.vector is not None:
            dim = len(d.vector)
            break
    return Corpus(documents=docs, dim=dim)


def _iter_docs(path: Path) -> Iterator[Document]:
    text = path.read_text()
    if path.suffix == ".jsonl":
        for line in text.splitlines():
            line = line.strip()
            if line:
                yield _to_doc(json.loads(line))
    else:
        data = json.loads(text)
        if not isinstance(data, list):
            raise ValueError(f"{path}: expected a JSON list of documents")
        for row in data:
            yield _to_doc(row)


def _to_doc(row: dict) -> Document:
    known = {"id", "text", "vector"}
    return Document(
        id=str(row["id"]),
        text=row.get("text"),
        vector=row.get("vector"),
        fields={k: v for k, v in row.items() if k not in known},
    )


def load_qrels(path: str | Path) -> Qrels:
    """Load relevance judgments. Accepts either:

    - {"q1": {"docA": 2, "docB": 1}, ...}
    - TREC-style lines "qid 0 docid rel"
    """
    p = Path(path)
    raw = p.read_text()
    stripped = raw.lstrip()
    if stripped.startswith("{"):
        obj = json.loads(raw)
        return {str(q): {str(d): int(r) for d, r in rels.items()} for q, rels in obj.items()}
    qrels: Qrels = {}
    for line in raw.splitlines():
        parts = line.split()
        if len(parts) == 4:
            qid, _, docid, rel = parts
            qrels.setdefault(qid, {})[docid] = int(rel)
    return qrels


def sample_queries_from_corpus(corpus: Corpus, n: int, seed: int = 0) -> QuerySet:
    """Hold out `n` documents to serve as queries (standard ANN-eval practice).

    Deterministic given `seed` (no wall-clock randomness) so runs are
    reproducible and resumable. The held-out docs are used as query
    vectors/text; the tool then computes exact top-k over the remaining corpus
    as recall ground truth.
    """
    if n <= 0 or not corpus.documents:
        return QuerySet(queries=[])
    count = len(corpus.documents)
    n = min(n, count)
    # Deterministic stride-based sampling — evenly spread, no RNG import.
    step = max(1, count // n)
    picked = corpus.documents[::step][:n]
    return QuerySet(
        queries=[Query(id=f"q::{d.id}", text=d.text, vector=d.vector) for d in picked]
    )
