"""ai-search-tuner CLI — the top-level orchestrator.

Ties the pieces together:
    probe capabilities → for each supported mode: generate configs (agentic
    pruning) → benchmark → flag regressions → recommend → render report.

Minimum input is a corpus alone (recall ground truth is generated by the tool);
`--qrels` is optional and unlocks NDCG/MAP relevance scoring.

Usage:
    ai-search-tuner --corpus ./data.jsonl
    ai-search-tuner --corpus ./data.jsonl --qrels ./qrels.json \
        --modes dense_knn,sparse_rank_features --k 10 \
        --quality-floor 0.95 --latency-budget-ms 100 --report out.html

Auth is read from environment (see harness/client.py). Read-only by default:
benchmarking builds only temporary indices on a sampled corpus and tears them
down. Nothing is applied to a production index without a separate,
confirmation-gated step (not part of this benchmark command).
"""

from __future__ import annotations

import argparse
import logging
import sys
from pathlib import Path

# Self-bootstrap the flat-layout module dirs onto sys.path so the tool runs with
# a plain `python3 scripts/ai_search_tuner_cli.py ...` — no PYTHONPATH prefix
# needed. (Modules import each other flatly, e.g. `from model import ...`.)
_SCRIPTS = Path(__file__).resolve().parent
for _p in (_SCRIPTS, _SCRIPTS / "harness", _SCRIPTS / "modes"):
    _sp = str(_p)
    if _sp not in sys.path:
        sys.path.insert(0, _sp)

# Flat imports (dirs added to sys.path just above).
from model import Capabilities, Measurement, Metric, Mode
from corpus import load_corpus, load_qrels, load_queries, sample_queries_from_corpus
import probe as probe_mod
from runner import benchmark
from pareto import recommend, flag_regressions
import report as report_mod

from dense_knn import DenseKnnPlugin
from sparse_rank_features import SparseRankFeaturesPlugin
from sparse_ann import SparseAnnPlugin
from hybrid import HybridPlugin

logger = logging.getLogger("ai_search_tuner")

# Registry of available mode plugins.
PLUGINS = {
    Mode.DENSE_KNN: DenseKnnPlugin,
    Mode.SPARSE_RANK_FEATURES: SparseRankFeaturesPlugin,
    Mode.SPARSE_ANN: SparseAnnPlugin,
    Mode.HYBRID: HybridPlugin,
}


def build_client(dry_run_version: str | None = None):
    """Construct a live client, or a FakeOSClient when --offline is set."""
    if dry_run_version is not None:
        # Offline demo: FakeOSClient is bundled in this skill's scripts/ (already
        # on sys.path via the module-level bootstrap), so --offline works from a
        # standalone `npx skills` install with no repo test tree present.
        from fake_client import FakeOSClient

        fake = FakeOSClient(version=dry_run_version)
        # Make the offline demo realistic: derive recall from ef_search + encoder
        # so the #21 silent-recall-drop story actually appears in the report.
        fake.model_recall_from_params = True
        return fake
    from client import RealOSClient

    return RealOSClient.from_env()


def parse_modes(arg: str | None, cap: Capabilities) -> list[Mode]:
    """Resolve requested modes ∩ supported modes. Default = all supported."""
    if arg:
        requested = []
        for tok in arg.split(","):
            tok = tok.strip()
            if not tok:
                continue
            try:
                requested.append(Mode(tok))
            except ValueError:
                logger.warning("unknown mode '%s' — ignoring", tok)
    else:
        requested = list(PLUGINS.keys())

    resolved = []
    for m in requested:
        if m not in PLUGINS:
            logger.warning("mode '%s' not implemented yet — skipping", m.value)
            continue
        # Gate on the PLUGIN's is_available(cap), not the raw capability flag.
        # The plugin encodes richer prerequisites (e.g. sparse/hybrid need a
        # DEPLOYED model, not just the plugin) — checking only cap.supports()
        # lets a modeless sparse/hybrid mode through and then 404s at query time.
        if not PLUGINS[m]().is_available(cap):
            logger.info("mode '%s' prerequisites not met — skipping (graceful degradation)", m.value)
            continue
        resolved.append(m)
    return resolved


def run(args: argparse.Namespace) -> dict[Mode, list[Measurement]]:
    corpus = load_corpus(args.corpus)
    logger.info("loaded corpus: %d documents (dim=%s)", len(corpus), corpus.dim)
    qrels = load_qrels(args.qrels) if args.qrels else None
    if qrels:
        logger.info("loaded qrels for %d queries (NDCG/MAP enabled)", len(qrels))

    client = build_client(dry_run_version=args.offline)
    cap = probe_mod.detect_capabilities(client)
    logger.info("\n%s", probe_mod.capability_summary(cap))

    # Queries: an explicit query set (real labeled eval, ids matching --qrels)
    # takes precedence; otherwise sample held-out documents from the corpus.
    if args.queries:
        queries = load_queries(args.queries)
        logger.info("loaded %d explicit queries from %s", len(queries), args.queries)
    else:
        queries = sample_queries_from_corpus(corpus, n=args.num_queries, seed=args.seed)
    if len(queries) == 0:
        logger.error("no queries could be derived from the corpus; aborting")
        return {}

    modes = parse_modes(args.modes, cap)
    if not modes:
        logger.error("no runnable modes for this cluster; nothing to do")
        return {}

    results: dict[Mode, list[Measurement]] = {}
    recommendations: dict[Mode, list[Measurement]] = {}
    # Each mode is ranked AND displayed on the SAME metric so the recommended
    # row never disagrees with the shown quality column. Approximate modes
    # (dense k-NN, sparse ANN) are ranked on RECALL-vs-exact; exact/relevance
    # modes (sparse rank_features, hybrid) are ranked on NDCG when qrels exist,
    # else on their overlap-vs-baseline (stored under RECALL).
    mode_metric: dict[Mode, Metric] = {}

    ks = tuple(sorted({5, args.k, 100}))

    def _bench(_plugin, _configs):
        return benchmark(
            plugin=_plugin,
            client=client,
            corpus=corpus,
            queries=queries,
            configs=_configs,
            qrels=qrels,
            ks=ks,
            quality_floor=args.quality_floor,
            latency_budget_ms=args.latency_budget_ms,
        )

    for mode in modes:
        plugin = PLUGINS[mode]()
        gen = plugin.config_generator()
        configs = gen.seed_configs(cap, corpus)
        logger.info("[%s] seeded %d configs", mode.value, len(configs))

        measurements = _bench(plugin, configs)
        if not measurements:
            logger.warning("[%s] produced no measurements", mode.value)
            continue

        # Agentic refinement (DESIGN §7): let the mode propose follow-up configs
        # from the results so far (e.g. sparse ANN lowers top_n once the recall
        # floor is met, to trade query terms for latency). Bounded rounds; stops
        # when refine() returns []. Dedupe by config label so we never re-run one.
        seen_labels = {m.config.label for m in measurements}
        for _round in range(args.max_refine_rounds):
            try:
                follow_ups = gen.refine(
                    measurements, args.quality_floor, args.latency_budget_ms
                )
            except Exception as e:  # a mode's refine must never abort the run
                logger.warning("[%s] refine() raised, stopping refinement: %s", mode.value, e)
                break
            follow_ups = [c for c in (follow_ups or []) if c.label not in seen_labels]
            if not follow_ups:
                break
            logger.info("[%s] refine round %d: %d follow-up config(s)",
                        mode.value, _round + 1, len(follow_ups))
            more = _bench(plugin, follow_ups)
            if not more:
                break
            seen_labels.update(m.config.label for m in more)
            measurements.extend(more)

        # Pick the metric this mode is graded on: NDCG for relevance modes when
        # qrels are present, otherwise the RECALL slot (recall-vs-exact for
        # approximate modes; overlap-vs-baseline for exact modes).
        use_ndcg = (not mode.is_approximate) and bool(qrels)
        rank_metric = Metric.NDCG if use_ndcg else Metric.RECALL
        mode_metric[mode] = rank_metric

        # Silent-regression detection (#21): reference = the GLOBAL best quality
        # on the metric we rank by. This is deliberate: if a latency/footprint
        # constraint later forces us to recommend a lower-quality config, that
        # config SHOULD still carry the flag — it surfaces exactly the "your
        # budget is silently costing you quality" story. The report explains a
        # flagged recommendation rather than hiding it (see report.py).
        best_q = max(
            (m.quality.get(rank_metric, args.k) or 0.0) for m in measurements
        )
        flag_regressions(measurements, rank_metric, args.k, ref_quality=best_q,
                          drop_threshold=args.regression_threshold)

        recs = recommend(
            measurements, rank_metric, args.k,
            quality_floor=args.quality_floor,
            latency_budget_ms=args.latency_budget_ms,
            top_n=3,
        )
        results[mode] = measurements
        recommendations[mode] = recs

    # Output — render each mode on its own ranking metric (no RECALL/NDCG mixup).
    print(report_mod.text_summary(results, recommendations, mode_metric, args.k))
    if args.report:
        meta = {"corpus_docs": len(corpus), "queries": len(queries),
                "version": cap.version, "qrels": bool(qrels)}
        if args.quality_floor is not None:
            meta["quality_floor"] = args.quality_floor
        html = report_mod.render_html(
            results, recommendations, mode_metric, args.k, meta=meta,
        )
        Path(args.report).write_text(html)
        logger.info("wrote HTML report → %s", args.report)

    return results


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(
        prog="ai-search-tuner",
        description="Benchmark and Pareto-tune OpenSearch retrieval "
                    "(dense k-NN, neural sparse, hybrid).",
    )
    p.add_argument("--corpus", required=True, help="JSON/JSONL corpus (minimum input)")
    p.add_argument("--qrels", help="optional relevance judgments (unlocks NDCG/MAP)")
    p.add_argument("--queries", help="optional explicit query set (JSON/JSONL: id/text/vector); "
                                     "ids should match --qrels. Default: sample held-out corpus docs.")
    p.add_argument("--modes", help="comma list: dense_knn,sparse_rank_features,... (default: all supported)")
    p.add_argument("--k", type=int, default=10, help="the k for quality@k ranking (default 10)")
    p.add_argument("--num-queries", type=int, default=50, dest="num_queries",
                   help="held-out queries sampled from corpus (default 50)")
    p.add_argument("--quality-floor", type=float, default=None, dest="quality_floor",
                   help="minimum acceptable quality@k, e.g. 0.95")
    p.add_argument("--latency-budget-ms", type=float, default=None, dest="latency_budget_ms",
                   help="maximum acceptable p95 latency in ms")
    p.add_argument("--regression-threshold", type=float, default=0.05,
                   dest="regression_threshold",
                   help="flag configs whose quality drops > this fraction below best (default 0.05)")
    p.add_argument("--max-refine-rounds", type=int, default=1, dest="max_refine_rounds",
                   help="agentic refinement rounds after the seed sweep (0 disables; "
                        "default 1). Modes may propose follow-up configs, e.g. sparse "
                        "ANN lowers top_n once the recall floor is met to cut latency.")
    p.add_argument("--report", help="path to write a self-contained HTML report")
    p.add_argument("--seed", type=int, default=0, help="deterministic query sampling seed")
    p.add_argument("--offline", metavar="VERSION", default=None,
                   help="run against an in-memory FakeOSClient of the given version "
                        "(smoke/demo without a cluster), e.g. --offline 2.17.1")
    p.add_argument("-v", "--verbose", action="store_true")
    args = p.parse_args(argv)

    logging.basicConfig(
        level=logging.INFO if args.verbose else logging.WARNING,
        format="%(message)s",
    )
    results = run(args)
    return 0 if results else 1


if __name__ == "__main__":
    raise SystemExit(main())
